### ISSUE TITLE
Non translatable string

### ISSUE THREAD

**Issue by cebas** [sovware/directorist#1126]
In /includes/modules/multi-directory-setup/class-multi-directory-manager.php, the string 'Price of this listing. Eg. 100' is not translatable.

**Comment by adminazhar** [comment]
@vairafiq @kowsar89 Will require re-generation of pot file, also i think whatever tools we are using it is ignoring that string.

**Comment by kowsar89** [comment]
These are dynamic values, can be changed by user input, screenshot: https://prnt.sc/Uhnj8uLrsESW
That's why we've kept it untranslatable.

**Comment by cebas** [comment]
Yes, is editable, but what I input there is not shown while adding a listing. Please, try it.
This happens on these labels: "Price Unit Field label" and "Price Unit Field Placeholder".

**Comment by richardaubin** [comment]
I agree with @cebas. Even though the strings are dynamic, for an admin who's using the site in another language, might not be able to understand the english defaults.  All strings should be translatable.
