### ISSUE TITLE
can't uncheck mark as featured

### ISSUE THREAD

**Issue by M4hd1BD** [sovware/directorist#1155]

**Comment by adminazhar** [comment]
@M4hd1BD Can you share more details, or screenshot.

**Comment by M4hd1BD** [comment]
Hey @adminazhar, if you have monetization with featured listing turned on and then if you mark a listing as featured (or a user makes a listing featured by paying), you can't unmark the 'mark as featured' metabox on the backend, you can unmark it but saving the change makes it marked again. This was discussed internally, this is here just for tracking.
