### ISSUE TITLE
listing submission notification doesn't close on dashboard

### ISSUE THREAD

**Issue by M4hd1BD** [sovware/directorist#1202]
https://i.imgur.com/lCxqeSO.png

**Comment by kowsar89** [comment]
How to regenerate this?

**Comment by M4hd1BD** [comment]
@kowsar89, set Redirect after Editing a listing to User Dashboard from Settings > Single Listing and then submit a listing, after submission, you'll be redirected to the Dashboard, try to get rid of the notification of the successful submission there.

**Comment by kowsar89** [comment]
Also notification styling seems broken

**Comment by kowsar89** [comment]
Notification reappear after reloading
