### ISSUE TITLE
All author page active indicator is missing

### ISSUE THREAD

**Issue by kowsar89** [sovware/directorist#1213]
### Directorist version

alpha, 7.3.4

### Description

In All Authors page, there's no active indicator after using the pagination.
https://ibb.co/ZmzGcL3

### Steps to reproduce

1. Go to All Authors page
2. Click on any pagination button

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

**Comment by devShamim** [comment]
https://prnt.sc/2TsPsHOIc5TH

Working fine here on my end
