### ISSUE TITLE
category based custom fields don't appear on first load if editing listing

### ISSUE THREAD

**Issue by M4hd1BD** [sovware/directorist#1223]
### Directorist version

Alpha (v7.4.1)

### Description

https://www.dropbox.com/s/pk5g3er9h88nwff/Directorist%20Bug%2001.mp4?dl=0

### Steps to reproduce

1. Add a custom field based on a specific category. 
2. Go to Add Listing, select that specific category and then fill out the info on that custom field. 
3. Go to Dashboard, Edit the listing that you just submitted, you'll see that the custom field isn't there, even though the category is selected. 

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022, etc).

**Comment by kowsar89** [comment]
Also it acts weird if custom field is in different section. Regeneration steps:

1. https://prnt.sc/MCunO-QiPY_g
2. https://prnt.sc/HiR7NXw51hMg
3. https://prnt.sc/-OrZt9ks7MUG

**Comment by kowsar89** [comment]
Also creates blank space: https://prnt.sc/9rD8p-ACoP_A
Ref: https://github.com/sovware/directorist/issues/1020
