### ISSUE TITLE
optimize get_users call on class-settings-panel and class-announcement 

### ISSUE THREAD

**Issue by M4hd1BD** [sovware/directorist#1229]
### Directorist version

7.4.1

### Description

this is not ideal for sites with large number of users, the server will run out of memory and it won't be possible to access the settings panel.

### Steps to reproduce

1. Have a site with a large number of users (over 30k or maybe less, depending on your server)
2. Go to Settings and you'll see its just returning blank page. If you see the logs you'll see memory out error. 

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

**Comment by M4hd1BD** [comment]
Temporary fix:
Limit the call to load 1k users only: 
![image](https://user-images.githubusercontent.com/37076749/196609694-e62ce76d-2de8-453e-929d-343331533289.png)
![image](https://user-images.githubusercontent.com/37076749/196609865-d015a767-7c1b-4f3b-9200-9802cae68226.png)

**Comment by kowsar89** [comment]
From https://10up.github.io/Engineering-Best-Practices/php/

Do not use posts_per_page => -1.

This is a performance hazard. What if we have 100,000 posts? This could crash the site. If you are writing a widget, for example, and just want to grab all of a custom post type, determine a reasonable upper limit for your situation.
```
<?php
// Query for 500 posts.
new WP_Query( array(
  'posts_per_page' => 500,
));
?>
```

**Comment by kowsar89** [comment]
> Temporary fix: Limit the call to load 1k users only: ![image](https://user-images.githubusercontent.com/37076749/196609694-e62ce76d-2de8-453e-929d-343331533289.png) ![image](https://user-images.githubusercontent.com/37076749/196609865-d015a767-7c1b-4f3b-9200-9802cae68226.png)

In that case, all users will not get the announcements
