### ISSUE TITLE
Sort by title and listing per page breaks on pagination with Instant Search

### ISSUE THREAD

**Issue by M4hd1BD** [sovware/directorist#1233]
### Directorist version

7.4.2(alpha)

### Description

Paginated pages don't respect sort by title, it shows listing randomly, it also doesn't respect the listing per page settings.

### Steps to reproduce

1. Settings > All Listing - Set Orderby Title and Sory By Ascending and also set Listing Per Page to 2. Also turn on Instant Search
2. Go to All Listings page, you'll see 2 listings, sorted by their title, lets say they start with A and B respectively
3. Now go to the Second page using the Paginator, you would expect it to show listings that start with C and D, but instead you will see more than 2 listings that doesn't follow the title sorting convention. 

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

**Comment by kowsar89** [comment]
Workaround: Keeping these settings same: https://prnt.sc/KKy7BWk90CrZ﻿
