### ISSUE TITLE
critical error on single listing

### ISSUE THREAD

**Issue by M4hd1BD** [sovware/directorist#1255]
### Directorist version

7.4.2.1

### Environment

PHP: 8.0.2.4
WordPress: 6.0
### Description

if zip field is deleted from the add listing form but not single listing form, it throws a critical error

`
[08-Nov-2022 06:04:09 UTC] PHP Fatal error:  Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in /home/virtuoso/public_html/wp-includes/class-wp-block-parser.php:417
Stack trace:
#0 /home/virtuoso/public_html/wp-includes/class-wp-block-parser.php(417): preg_match('/<!--\\s+(?P<clo...', Array, NULL, 256, 0)
#1 /home/virtuoso/public_html/wp-includes/class-wp-block-parser.php(256): WP_Block_Parser->next_token()
#2 /home/virtuoso/public_html/wp-includes/class-wp-block-parser.php(236): WP_Block_Parser->proceed()
#3 /home/virtuoso/public_html/wp-includes/blocks.php(923): WP_Block_Parser->parse(Array)
#4 /home/virtuoso/public_html/wp-includes/blocks.php(649): parse_blocks(Array)
#5 /home/virtuoso/public_html/wp-includes/formatting.php(5088): filter_block_content(Array, 'post', Array)
#6 /home/virtuoso/public_html/wp-includes/class-wp-hook.php(307): wp_pre_kses_block_attributes(Array, 'post', Array)
#7 /home/virtuoso/public_html/wp-includes/plugin.php(191): WP_Hook->apply_filters(Array, Array)
#8 /home/virtuoso/public_html/wp-includes/kses.php(909): apply_filters('pre_kses', Array, 'post', Array)
#9 /home/virtuoso/public_html/wp-includes/kses.php(719): wp_kses_hook(Array, 'post', Array)
#10 /home/virtuoso/public_html/wp-includes/kses.php(2106): wp_kses(Array, 'post')
#11 /home/virtuoso/public_html/wp-content/plugins/directorist/templates/single/fields/zip.php(18): wp_kses_post(Array)
#12 /home/virtuoso/public_html/wp-content/plugins/directorist/includes/helpers/trait-uri-helper.php(70): include('/home/virtuoso/...')
#13 /home/virtuoso/public_html/wp-content/plugins/directorist/includes/model/SingleListing.php(269): Directorist\Helper::get_template('single/fields/z...', Array)
#14 /home/virtuoso/public_html/wp-content/plugins/directorist/templates/single/section-general.php(24): Directorist\Directorist_Single_Listing->field_template(Array)
#15 /home/virtuoso/public_html/wp-content/plugins/directorist/includes/helpers/trait-uri-helper.php(70): include('/home/virtuoso/...')
#16 /home/virtuoso/public_html/wp-content/plugins/directorist/includes/model/SingleListing.php(147): Directorist\Helper::get_template('single/section-...', Array)
#17 /home/virtuoso/public_html/wp-content/themes/onelisting/directorist/single-contents.php(84): Directorist\Directorist_Single_Listing->section_template(Array)
#18 /home/virtuoso/public_html/wp-content/plugins/directorist/includes/helpers/trait-uri-helper.php(70): include('/home/virtuoso/...')
#19 /home/virtuoso/public_html/wp-content/themes/onelisting/directorist/single.php(22): Directorist\Helper::get_template('single-contents')
#20 /home/virtuoso/public_html/wp-includes/template-loader.php(106): include('/home/virtuoso/...')
#21 /home/virtuoso/public_html/wp-blog-header.php(19): require_once('/home/virtuoso/...')
#22 /home/virtuoso/public_html/index.php(17): require('/home/virtuoso/...')
#23 {main}
  thrown in /home/virtuoso/public_html/wp-includes/class-wp-block-parser.php on line 417
`

### Steps to reproduce

1. Add the Zip Code field to the Add Listing Form
2. Add the Zip Code field to the Single Page Layout
3. Delete the Zip Code field from the Add Listing Form
4. Submit a listing, go to the Preview/Single Listing Page for that listing, you'll see the error

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

**Comment by kowsar89** [comment]
Also creates php warning in php v7.4: http://prntscr.com/01sizeUG_Uqm
