### ISSUE TITLE
Unwanted code in account.js, conflicting with single-listing.js

### ISSUE THREAD

**Issue by HeyMehedi** [sovware/directorist#1268]
### Directorist version

latest

### Environment

any

### Description

While using the account.js script for popup login and registration. the single listing report button "login alert" shows twice. 

I checked and understand that some code is duplicated in the account.js 
**path** directorist/assets/js/account.js
**line number** 208-212

### Steps to reproduce

To reproduce the issue, please use the OneListing Theme.

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [ ] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

**Comment by devShamim** [comment]
#1279
