### ISSUE TITLE
[Improvement] Select field down arrow should reveal the dropdown

### ISSUE THREAD

**Issue by M4hd1BD** [sovware/directorist#1277]
### Directorist version

v7.4.4

### Description

these should reveal the dropwdown: 
![image](https://user-images.githubusercontent.com/37076749/203715574-c075bffc-cd87-46e3-8d41-4e2ebee9a7d7.png)

### Steps to reproduce

Check filters on All Listing Page

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

**Comment by claytonwinterbotham** [comment]
Any updates on this? Our users think the drop down is broken because the arrow is not clickable.

**Comment by devShamim** [comment]
@iamibrahimriaz please take care of this issue
