### ISSUE TITLE
admin only fields data getting wiped if user edits the lisitng

### ISSUE THREAD

**Issue by M4hd1BD** [sovware/directorist#1278]
### Directorist version

v7.4.4

### Description

Admin Only fields data gets deleted as if the user submitted a listing without adding any data to the field 

### Steps to reproduce

1. Submit a listing as a user in the front end. 
2. Have an admin-only field like View Count, and add some data to it from the backend. 
3. Edit the listing on the frontend from the users account
4. Check the listing on the backend again, you'll see the data you added on step 2 got deleted

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

**Comment by kowsar89** [comment]
"Edit the listing on the frontend from the users account" -> this is admin only field, user is not able to edit account
