### ISSUE TITLE
need listing fields not appearing on single listing page

### ISSUE THREAD

**Issue by M4hd1BD** [sovware/directorist#1302]
### Directorist version

v7.4.6

### Description

fields are not showign up

### Steps to reproduce

1. Install and Activate Post Your Need
2. Add a listing to the directory that was automatically created
3. View the listing on the frontend

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

**Comment by kowsar89** [comment]
Probably extension issue, not core
