### ISSUE TITLE
location detector doesn't work after category selection 

### ISSUE THREAD

**Issue by M4hd1BD** [sovware/directorist#1305]
### Directorist version

Alpha

### Description

The current location detector, that detects the current location of the user on the location search box doesn't work after selecting a category

### Steps to reproduce

https://www.loom.com/share/8be7d90d450c425ca24f828c30945df8

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

**Comment by devShamim** [comment]
@iamibrahimriaz
