### ISSUE TITLE
Removing All New Line in Textarea

### ISSUE THREAD

**Issue by HeyMehedi** [sovware/directorist#1425]
### Directorist version

latest

### Environment

all

### Description

I was testing the dJobs theme with the latest directorist extension. When adding content to the " bullet list " requires inserting new lines for each bullet. It was working on the previous version 7.5.1. So I think this issue was raised in the new version. and It exists in the Textarea field.

### Steps to reproduce

1. Install the Latest Directorist
2. Use any Default theme
3. Add a textarea field from Builder -> Add Listing Form 
4. Go to Add Listing page
5. Put some text in multiple lines.
6.  Submit the listing form 
7. Go to the single listing page, you will see all list items showing in single line

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

**Comment by vairafiq** [comment]
The default custom field textarea has the same issue

**Comment by obiPlabon** [comment]
I got the issue even with `v7.5.1`! Anyway, I've added more precise sanitization on #1423
