### ISSUE TITLE
WP-CLI - PHP Warning:  Undefined array key "HTTP_HOST" in wp-content/plugins/directorist/includes/modules/appsero/src/Insights.php on line 360

### ISSUE THREAD

**Issue by ethanclevenger91** [sovware/directorist#1490]
### Directorist version

7.5.4

### Environment

PHP 8.1.9
the7 theme
WP 6.2.whatever-the-latest-one-is

### Description

When running WP-CLI commands on a site w/ Directorist active, the title warning appears in the terminal.

This is actually in the Appsero code used for usage tracking, and seems to be resolved in [their latest release](https://github.com/Appsero/client/blob/v1.2.3/src/Insights.php#L370).

### Steps to reproduce

1. Configure a WP install
2. Install Directorist
3. Activate Directorist
4. Run `wp help` on the command line

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

**Comment by damen02** [comment]
Same problem here, any lead or solution?

**Comment by obiPlabon** [comment]
@ethanclevenger91 @damen02 This issue has been fixed by updating the Appsero client library.

Thank you :)
