### ISSUE TITLE
The "Go Back" button is not functioning correctly

### ISSUE THREAD

**Issue by a1amin** [sovware/directorist#1690]
### Directorist version

v7.8.2

### Description

The "Go back" button on the single listing page does not work with a single click but works if the user clicks it twice or multiple times. 

![image](https://github.com/sovware/directorist/assets/22941952/83c17892-895a-43aa-b2e3-e35419312f37)

### Steps to reproduce

Just go to a single listing page and click the "Go Back" button. It is expected to function correctly with the first click, but currently, it only works after the user clicks it two or three times.

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

**Comment by dimalif** [comment]
If you refresh the single page, the Go Back is gone.
