### ISSUE TITLE
Slow get_users query running on each page load

### ISSUE THREAD

**Issue by mikemanger** [sovware/directorist#325]
I have noticed that a get_users query in ATBDP_Settings_Panel is running on each page load. As far as I can tell it is only really needed on the announcement settings page itself. On a site with 2000 users this is adding about .3 seconds to the page load.

**Comment by obiPlabon** [comment]
Hi @mikemanger

Thank you for reporting the issue and sorry for the late response. Our dev team is working on it. Hopefully, this issue will be resolved in the next update.

Thanks again for supporting Directorist :)

**Comment by obiPlabon** [comment]
Hello @mikemanger 

Hope you are doing well and safe. You'll be happy to know that our devs already fixed the issue and it's in PR now - https://github.com/sovware/directorist/pull/333

Thank you

**Comment by obiPlabon** [comment]
This issue has been fixed and released.
