### ISSUE TITLE
atbdp_import_listing() not setting atbdp_listing_types term

### ISSUE THREAD

**Issue by fstilman** [sovware/directorist#385]
When importing listings from a CSV, atbdp_listing_types taxonomy is not being set on created posts. At least one consequence of this is that when trying to Edit a listing from the frontend it fails showing the form without fields (just a submit button).

If I manually set the atbdp_listing_types term for the post, the issue is solved. The problem seems to be with a missing line like the following:

wp_set_object_terms($post_id, (int)$directory_type, 'atbdp_listing_types')

That line is on directorist/includes/classes/class-add-listing.php but not on directorist/includes/classes/class-tools.php

Steps to replicate:

1) Tested with multi-directory mode OFF (just the general default directory)

2) Submit a new listing from frontend. Check in table term_relationships that directory type was correctly associated with the new post.

3) Import a new listing from CSV. Verift that no directory type is added to term_relationship.

Directorist plugin version is 7.0.5.1

**Comment by obiPlabon** [comment]
Hi @fstilman, sorry for the inconvenience and thank you for reporting the issue. This issue has been solved and merged to the `alpha` branch (#400). Your suggestion really helped us to solve it quickly and we are grateful for that :) The fix will be available in our upcoming release.

Thank you.
