### ISSUE TITLE
Override plugin templates

### ISSUE THREAD

**Issue by piefus** [sovware/directorist#57]
Is there a way to override the default templates in a child theme?

**Comment by damen02** [comment]
I have the same question. Specifically by now, I need to change the location of custom fields that are displayed in the "_Add listing frontend form_", _add-listing.php_ I guess. Thanks!

**Comment by blueocto** [comment]
This would make the plugin more useable, semantic, accessible... for theme developers. Any idea of a timescale on this?

**Comment by aazztech** [comment]
This is already live in _directorist-beta_ branch. Please checkout the branch and let us know. [Documentation](https://directorist.com/documentation/directorist/developers-guide/theming/)

**Comment by kowsar89** [comment]
This feature is available now: https://directorist.com/documentation/directorist/developers-guide/template-override/
