### ISSUE TITLE
Please could you help with search

### ISSUE THREAD

**Issue by Kasby** [sovware/directorist#59]
Greetings
We are using your plugin to list a bunch of factory shops.
However, when I put the search in, the results always show absolutely nothing.
I have even added tags on the individual listings, but still no luck.

The site is here www.factoryshopssa.co.za - by the find button. We have added all the listings, but really need some kind of search feature here... please help.

**Comment by jaimeocampo** [comment]
Hello, did you have an answer from Directorist Support? I have the same issue with a specific template. With WP twenty-twenty it works good. Any workaround?

**Comment by witch3r** [comment]
Hello @Kasby and @jaimeocampo 

We are sorry for the delayed response. We actively provide support on the WP forum as well as through our ticketing system. However, we will try to be active on GitHub from now on as well. 

Would you mind sharing the name of the theme, so we could test locally and check what causing the issue?

Regards,
