### ISSUE TITLE
reset filter not working on search result page as well as address (lang, long remains on the url)

### ISSUE THREAD

**Issue by M4hd1BD** [sovware/directorist#714]
Search for listings and then try the reset button and search again, check the URL and you’ll see lat, long, and miles value is still the old one
https://lobby.sovware.com/wp-admin/admin.php?page=pm_projects#/projects/8/task-lists/tasks/728

**Comment by M4hd1BD** [comment]
Possible duplicate: https://www.loom.com/share/c20630dfd642413585fedd62d2683364
Possible fix; #740

**Comment by devShamim** [comment]
Possible fix: #922 

@M4hd1BD @vairafiq Please check

**Comment by M4hd1BD** [comment]
Partially fixed.

**Comment by tanjimhasan** [comment]
@Armanul46 & @vairafiq please separate the data-slider attributes from /.directorist-range-slider DOM.

**Comment by vairafiq** [comment]
#937 attached @M4hd1BD please check

**Comment by M4hd1BD** [comment]
Fixed @vairafiq @tanjimhasan
