### ISSUE TITLE
Password Recovery - Set new password 

### ISSUE THREAD

**Issue by dimalif** [sovware/directorist#797]
After asking for recovery of password, in that page that asks for new password, the SAVE doesn't work. It doesn't do anything.

So password recovery doesn't work.

![Screenshot](https://user-images.githubusercontent.com/53921528/159927993-3b0c24dc-b7ec-4b89-80b7-df271374da62.png)

**Comment by dimalif** [comment]
I would like to kindly request to prioritize this check. 

Since we migrated the users, the passwords must be changed from the users and password recovery is the only way. Otherwise they can't login.

**Comment by M4hd1BD** [comment]
Hi @dimalif,

Are you using the OneListing theme? Could you please confirm if it doesn't work with Directorist + Any default WordPress Theme (Twenty-Twenty One, etc)?

**Comment by eurobank** [comment]
I used Onelisting free theme.

**Comment by M4hd1BD** [comment]
Hey @eurobank,

This is a known issue of the OneListing Theme itself, it's not a directorist issue. I've already passed it on to the relevant team for fix.
