### ISSUE TITLE
Membership - Anyone can register - Not Respected

### ISSUE THREAD

**Issue by dimalif** [sovware/directorist#800]
**Anyone can register** Wordpress option is not respected. 

While we selected not to allow registrations for the moment, it seems anyone can register.

![Screenshot](https://user-images.githubusercontent.com/53921528/159942972-e19c7cf2-63a2-4e2d-ade9-7e77d7a7f0d5.png)

**Comment by vairafiq** [comment]
@dimalif could you please check the discussion on #840
