### ISSUE TITLE
Number of Images allowed to upload

### ISSUE THREAD

**Issue by dimalif** [sovware/directorist#801]
There two issues with that:

1. Wrong wording in posting form: "Minimum number of images to upload: 4" should be "Maximum ......"

2. When more than the defined MAX images are uploaded, there is no error warning, the page just doesn't publish. This is extremely confusing to the user. The user doesn't know what the issue is.

3. Why the 1st text shows 5 and the next shows 4? 

![Screenshot](https://user-images.githubusercontent.com/53921528/160127504-24ac2641-07d7-425e-8613-0ac4597884e1.png)

**Comment by dimalif** [comment]
Extractly the same issue at your own demo at 

https://demo.directorist.com/theme/onelisting-pro/add-listing/?directory_type=restaurants&plan=1091


![Screenshot](https://user-images.githubusercontent.com/53921528/160131409-e60254f9-2107-4ade-b095-4407d225d0b2.png)

**Comment by dimalif** [comment]
Not an issue. My mistake.

**Comment by dimalif** [comment]
Actually this is only a typo, The Minimum should be worded Maximum.

**Comment by vairafiq** [comment]
Thanks for reporting this. We have fixed the issue and will released the fixed version ([oneListing](https://directorist.com/product/onelisting/)) shortly
